In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df=pd.read_csv('D:\Python Projects\Multi_Home.csv')

In [13]:
df

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [8]:
import math
median_bedroom=math.floor(df.Bedrooms.median())
median_bedroom

3

In [10]:
df.Bedrooms[2]=median_bedroom

<ipython-input-10-98995d723d00>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Bedrooms[2]=median_bedroom


In [12]:
df.Bedrooms[2]

3.0

In [15]:
reg_obj=linear_model.LinearRegression()
reg_obj.fit(df[['Area','Bedrooms','Age']], df.Price)

LinearRegression()

In [16]:
reg_obj.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [17]:
reg_obj.intercept_

383724.9999999998

In [18]:
reg_obj.predict([[3000, 4, 40]])

array([418375.])

In [19]:
reg_obj.predict([[2500, 4, 5]])

array([588625.])